// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project01

#ifndef _UI_COMP_ITEM_H
#define _UI_COMP_ITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT item
#define UI_COMP_ITEM_ITEM 0
#define UI_COMP_ITEM_LABEL1 1
#define _UI_COMP_ITEM_NUM 2
lv_obj_t * ui_item_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
