// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project01

#include "../ui.h"


// COMPONENT item

lv_obj_t * ui_item_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_item;
    cui_item = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_item, 60);
    lv_obj_set_width(cui_item, lv_pct(100));
    lv_obj_set_align(cui_item, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_item, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_item, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_item);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_recolor(cui_Label1, "true");
    lv_obj_set_style_text_color(cui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_Label1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ITEM_NUM);
    children[UI_COMP_ITEM_ITEM] = cui_item;
    children[UI_COMP_ITEM_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_item, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_item, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_item_create_hook(cui_item);
    return cui_item;
}

