// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project01

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_Header;
lv_obj_t * ui_DateLabel;
lv_obj_t * ui_TimeLabel;
lv_obj_t * ui_HeaderTitle;
lv_obj_t * ui_MainLeftPannel;
lv_obj_t * ui_TotalVoltage10;
lv_obj_t * ui_TotalVoltage;
lv_obj_t * ui_TotalAmpere;
lv_obj_t * ui_TotalTemperature;
lv_obj_t * ui_TotalVoltageLabel;
lv_obj_t * ui_HighVoltage;
lv_obj_t * ui_LowVoltage;
lv_obj_t * ui_AverageVoltage;
lv_obj_t * ui_HighImpedance;
lv_obj_t * ui_LowImpedance;
lv_obj_t * ui_AverageImpendance;
void ui_event_ChangeModule(lv_event_t * e);
lv_obj_t * ui_ChangeModule;
lv_obj_t * ui_Label9;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_MainRightPannel;
lv_obj_t * ui_CellInfo1;
lv_obj_t * ui_CellNo1;
lv_obj_t * ui_voltage1;
lv_obj_t * ui_impedance1;
lv_obj_t * ui_CellInfo2;
lv_obj_t * ui_CellNo2;
lv_obj_t * ui_voltage2;
lv_obj_t * ui_impedance2;
lv_obj_t * ui_CellInfo3;
lv_obj_t * ui_CellNo3;
lv_obj_t * ui_voltage3;
lv_obj_t * ui_impedance3;
lv_obj_t * ui_CellInfo4;
lv_obj_t * ui_CellNo4;
lv_obj_t * ui_voltage4;
lv_obj_t * ui_impedance4;
lv_obj_t * ui_CellInfo5;
lv_obj_t * ui_CellNo5;
lv_obj_t * ui_voltage5;
lv_obj_t * ui_impedance5;
lv_obj_t * ui_CellInfo6;
lv_obj_t * ui_CellNo6;
lv_obj_t * ui_voltage6;
lv_obj_t * ui_impedance6;
lv_obj_t * ui_CellInfo7;
lv_obj_t * ui_CellNo7;
lv_obj_t * ui_voltage7;
lv_obj_t * ui_impedance7;
lv_obj_t * ui_CellInfo8;
lv_obj_t * ui_CellNo8;
lv_obj_t * ui_voltage8;
lv_obj_t * ui_impedance8;
lv_obj_t * ui_CellInfo9;
lv_obj_t * ui_CellNo9;
lv_obj_t * ui_voltage9;
lv_obj_t * ui_impedance9;
lv_obj_t * ui_CellInfo10;
lv_obj_t * ui_CellNo10;
lv_obj_t * ui_voltage10;
lv_obj_t * ui_impedance10;
lv_obj_t * ui_CellInfo11;
lv_obj_t * ui_CellNo11;
lv_obj_t * ui_voltage11;
lv_obj_t * ui_impedance11;
lv_obj_t * ui_CellInfo12;
lv_obj_t * ui_CellNo12;
lv_obj_t * ui_voltage12;
lv_obj_t * ui_impedance12;
lv_obj_t * ui_CellInfo13;
lv_obj_t * ui_CellNo13;
lv_obj_t * ui_voltage13;
lv_obj_t * ui_impedance13;
lv_obj_t * ui_CellInfo14;
lv_obj_t * ui_CellNo14;
lv_obj_t * ui_voltage14;
lv_obj_t * ui_impedance14;
lv_obj_t * ui_CellInfo15;
lv_obj_t * ui_CellNo15;
lv_obj_t * ui_voltage15;
lv_obj_t * ui_impedance15;
lv_obj_t * ui_CellInfo16;
lv_obj_t * ui_CellNo16;
lv_obj_t * ui_voltage16;
lv_obj_t * ui_impedance16;
lv_obj_t * ui_CellInfo17;
lv_obj_t * ui_CellNo17;
lv_obj_t * ui_voltage17;
lv_obj_t * ui_impedance17;
lv_obj_t * ui_CellInfo18;
lv_obj_t * ui_CellNo18;
lv_obj_t * ui_voltage18;
lv_obj_t * ui_impedance18;
lv_obj_t * ui_CellInfo19;
lv_obj_t * ui_CellNo19;
lv_obj_t * ui_voltage19;
lv_obj_t * ui_impedance19;
lv_obj_t * ui_CellInfo20;
lv_obj_t * ui_CellNo20;
lv_obj_t * ui_voltage20;
lv_obj_t * ui_impedance20;
lv_obj_t * ui_MainBottomPannel;
lv_obj_t * ui_CompanyLabel;
lv_obj_t * ui_CompanyLabel1;
lv_obj_t * ui_VersionLabel;


// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t * ui_SettingScreen;
lv_obj_t * ui_SetHeader;
lv_obj_t * ui_DateLabel1;
lv_obj_t * ui_TimeLabel1;
lv_obj_t * ui_HeaderTitle1;
lv_obj_t * ui_SetLeftPannel;
lv_obj_t * ui_TotalVoltage1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
void ui_event_SaveSettingButton(lv_event_t * e);
lv_obj_t * ui_SaveSettingButton;
lv_obj_t * ui_Label8;
lv_obj_t * ui_SetRightPannel;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label3;
void ui_event_HighVoltageTxt(lv_event_t * e);
lv_obj_t * ui_HighVoltageTxt;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label4;
void ui_event_LowVoltageTxt(lv_event_t * e);
lv_obj_t * ui_LowVoltageTxt;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label5;
void ui_event_HighTempTxt(lv_event_t * e);
lv_obj_t * ui_HighTempTxt;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label6;
void ui_event_HighImpTxt(lv_event_t * e);
lv_obj_t * ui_HighImpTxt;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label7;
lv_obj_t * ui_alarmSetStatus;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_SetBottomPannel;
lv_obj_t * ui_CompanyLabel2;
lv_obj_t * ui_CompanyLabel3;
lv_obj_t * ui_VersionLabel1;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ChangeModule(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        ChangeModuleEvent(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingScreen_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_SaveSettingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        saveButtenEvent(e);
    }
}
void ui_event_HighVoltageTxt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_HighVoltageTxt);
    }
}
void ui_event_LowVoltageTxt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_LowVoltageTxt);
    }
}
void ui_event_HighTempTxt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_HighTempTxt);
    }
}
void ui_event_HighImpTxt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_HighImpTxt);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_SettingScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
