// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project01

#ifndef _SQUARELINE_PROJECT01_UI_H
#define _SQUARELINE_PROJECT01_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_DateLabel;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_HeaderTitle;
extern lv_obj_t *ui_MainLeftPannel;
extern lv_obj_t *ui_TotalVoltage10;
extern lv_obj_t *ui_TotalVoltage;
extern lv_obj_t *ui_TotalAmpere;
extern lv_obj_t *ui_TotalTemperature;
extern lv_obj_t *ui_TotalVoltageLabel;
extern lv_obj_t *ui_HighVoltage;
extern lv_obj_t *ui_LowVoltage;
extern lv_obj_t *ui_AverageVoltage;
extern lv_obj_t *ui_HighImpedance;
extern lv_obj_t *ui_LowImpedance;
extern lv_obj_t *ui_AverageImpendance;
void ui_event_ChangeModule( lv_event_t * e);
extern lv_obj_t *ui_ChangeModule;
extern lv_obj_t *ui_Label9;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_MainRightPannel;
extern lv_obj_t *ui_CellInfo1;
extern lv_obj_t *ui_CellNo1;
extern lv_obj_t *ui_voltage1;
extern lv_obj_t *ui_impedance1;
extern lv_obj_t *ui_CellInfo2;
extern lv_obj_t *ui_CellNo2;
extern lv_obj_t *ui_voltage2;
extern lv_obj_t *ui_impedance2;
extern lv_obj_t *ui_CellInfo3;
extern lv_obj_t *ui_CellNo3;
extern lv_obj_t *ui_voltage3;
extern lv_obj_t *ui_impedance3;
extern lv_obj_t *ui_CellInfo4;
extern lv_obj_t *ui_CellNo4;
extern lv_obj_t *ui_voltage4;
extern lv_obj_t *ui_impedance4;
extern lv_obj_t *ui_CellInfo5;
extern lv_obj_t *ui_CellNo5;
extern lv_obj_t *ui_voltage5;
extern lv_obj_t *ui_impedance5;
extern lv_obj_t *ui_CellInfo6;
extern lv_obj_t *ui_CellNo6;
extern lv_obj_t *ui_voltage6;
extern lv_obj_t *ui_impedance6;
extern lv_obj_t *ui_CellInfo7;
extern lv_obj_t *ui_CellNo7;
extern lv_obj_t *ui_voltage7;
extern lv_obj_t *ui_impedance7;
extern lv_obj_t *ui_CellInfo8;
extern lv_obj_t *ui_CellNo8;
extern lv_obj_t *ui_voltage8;
extern lv_obj_t *ui_impedance8;
extern lv_obj_t *ui_CellInfo9;
extern lv_obj_t *ui_CellNo9;
extern lv_obj_t *ui_voltage9;
extern lv_obj_t *ui_impedance9;
extern lv_obj_t *ui_CellInfo10;
extern lv_obj_t *ui_CellNo10;
extern lv_obj_t *ui_voltage10;
extern lv_obj_t *ui_impedance10;
extern lv_obj_t *ui_CellInfo11;
extern lv_obj_t *ui_CellNo11;
extern lv_obj_t *ui_voltage11;
extern lv_obj_t *ui_impedance11;
extern lv_obj_t *ui_CellInfo12;
extern lv_obj_t *ui_CellNo12;
extern lv_obj_t *ui_voltage12;
extern lv_obj_t *ui_impedance12;
extern lv_obj_t *ui_CellInfo13;
extern lv_obj_t *ui_CellNo13;
extern lv_obj_t *ui_voltage13;
extern lv_obj_t *ui_impedance13;
extern lv_obj_t *ui_CellInfo14;
extern lv_obj_t *ui_CellNo14;
extern lv_obj_t *ui_voltage14;
extern lv_obj_t *ui_impedance14;
extern lv_obj_t *ui_CellInfo15;
extern lv_obj_t *ui_CellNo15;
extern lv_obj_t *ui_voltage15;
extern lv_obj_t *ui_impedance15;
extern lv_obj_t *ui_CellInfo16;
extern lv_obj_t *ui_CellNo16;
extern lv_obj_t *ui_voltage16;
extern lv_obj_t *ui_impedance16;
extern lv_obj_t *ui_CellInfo17;
extern lv_obj_t *ui_CellNo17;
extern lv_obj_t *ui_voltage17;
extern lv_obj_t *ui_impedance17;
extern lv_obj_t *ui_CellInfo18;
extern lv_obj_t *ui_CellNo18;
extern lv_obj_t *ui_voltage18;
extern lv_obj_t *ui_impedance18;
extern lv_obj_t *ui_CellInfo19;
extern lv_obj_t *ui_CellNo19;
extern lv_obj_t *ui_voltage19;
extern lv_obj_t *ui_impedance19;
extern lv_obj_t *ui_CellInfo20;
extern lv_obj_t *ui_CellNo20;
extern lv_obj_t *ui_voltage20;
extern lv_obj_t *ui_impedance20;
extern lv_obj_t *ui_MainBottomPannel;
extern lv_obj_t *ui_CompanyLabel;
extern lv_obj_t *ui_CompanyLabel1;
extern lv_obj_t *ui_VersionLabel;
// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t *ui_SettingScreen;
extern lv_obj_t *ui_SetHeader;
extern lv_obj_t *ui_DateLabel1;
extern lv_obj_t *ui_TimeLabel1;
extern lv_obj_t *ui_HeaderTitle1;
extern lv_obj_t *ui_SetLeftPannel;
extern lv_obj_t *ui_TotalVoltage1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
void ui_event_SaveSettingButton( lv_event_t * e);
extern lv_obj_t *ui_SaveSettingButton;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_SetRightPannel;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label3;
void ui_event_HighVoltageTxt( lv_event_t * e);
extern lv_obj_t *ui_HighVoltageTxt;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label4;
void ui_event_LowVoltageTxt( lv_event_t * e);
extern lv_obj_t *ui_LowVoltageTxt;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label5;
void ui_event_HighTempTxt( lv_event_t * e);
extern lv_obj_t *ui_HighTempTxt;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label6;
void ui_event_HighImpTxt( lv_event_t * e);
extern lv_obj_t *ui_HighImpTxt;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_alarmSetStatus;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_SetBottomPannel;
extern lv_obj_t *ui_CompanyLabel2;
extern lv_obj_t *ui_CompanyLabel3;
extern lv_obj_t *ui_VersionLabel1;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_Arial);
LV_FONT_DECLARE( ui_font_arial14);
LV_FONT_DECLARE( ui_font_arial16);
LV_FONT_DECLARE( ui_font_arial26);
LV_FONT_DECLARE( ui_font_arial28);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Greek);
LV_FONT_DECLARE( ui_font_malgunFont1);
LV_FONT_DECLARE( ui_font_montserrat16);
LV_FONT_DECLARE( ui_font_montserrat26);
LV_FONT_DECLARE( ui_font_montserrat28);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
