// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project01

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingScreen, lv_color_hex(0x4C4B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetHeader = lv_obj_create(ui_SettingScreen);
    lv_obj_set_width(ui_SetHeader, lv_pct(100));
    lv_obj_set_height(ui_SetHeader, lv_pct(10));
    lv_obj_set_align(ui_SetHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_SetHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetHeader, lv_color_hex(0x2F2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SetHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SetHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SetHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SetHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel1 = lv_label_create(ui_SetHeader);
    lv_obj_set_width(ui_DateLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DateLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DateLabel1, "2023-11-03");
    lv_obj_set_style_text_color(ui_DateLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel1 = lv_label_create(ui_SetHeader);
    lv_obj_set_width(ui_TimeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TimeLabel1, "PM 8:35");
    lv_obj_set_style_text_color(ui_TimeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderTitle1 = lv_label_create(ui_SetHeader);
    lv_obj_set_width(ui_HeaderTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaderTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HeaderTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeaderTitle1, "BMS SETTING");
    lv_obj_set_style_text_color(ui_HeaderTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaderTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderTitle1, &ui_font_arial28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetLeftPannel = lv_obj_create(ui_SettingScreen);
    lv_obj_set_width(ui_SetLeftPannel, lv_pct(20));
    lv_obj_set_height(ui_SetLeftPannel, lv_pct(80));
    lv_obj_set_x(ui_SetLeftPannel, 1);
    lv_obj_set_y(ui_SetLeftPannel, 0);
    lv_obj_set_align(ui_SetLeftPannel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_SetLeftPannel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SetLeftPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SetLeftPannel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetLeftPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetLeftPannel, lv_color_hex(0x353030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetLeftPannel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetLeftPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TotalVoltage1 = lv_label_create(ui_SetLeftPannel);
    lv_obj_set_height(ui_TotalVoltage1, lv_pct(80));
    lv_obj_set_width(ui_TotalVoltage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_TotalVoltage1, 2);
    lv_obj_set_y(ui_TotalVoltage1, 9);
    lv_label_set_text(ui_TotalVoltage1, "SYSTEM SET");
    lv_obj_set_style_text_color(ui_TotalVoltage1, lv_color_hex(0x1401F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TotalVoltage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_SetLeftPannel);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "메 인");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_malgunFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveSettingButton = lv_btn_create(ui_SetLeftPannel);
    lv_obj_set_width(ui_SaveSettingButton, 100);
    lv_obj_set_height(ui_SaveSettingButton, 30);
    lv_obj_set_x(ui_SaveSettingButton, -1);
    lv_obj_set_y(ui_SaveSettingButton, -39);
    lv_obj_set_align(ui_SaveSettingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveSettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveSettingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveSettingButton, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveSettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_SaveSettingButton);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "저 장");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_malgunFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetRightPannel = lv_obj_create(ui_SettingScreen);
    lv_obj_set_width(ui_SetRightPannel, lv_pct(80));
    lv_obj_set_height(ui_SetRightPannel, lv_pct(80));
    lv_obj_set_align(ui_SetRightPannel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_SetRightPannel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SetRightPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SetRightPannel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetRightPannel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetRightPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetRightPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SetRightPannel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SetRightPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SetRightPannel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SetRightPannel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_SetRightPannel);
    lv_obj_set_height(ui_Panel1, lv_pct(100));
    lv_obj_set_flex_grow(ui_Panel1, 1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x381616), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel3);
    lv_obj_set_height(ui_Label3, 30);
    lv_obj_set_width(ui_Label3, lv_pct(70));
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "High Voltage(V)");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighVoltageTxt = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_HighVoltageTxt, lv_pct(30));
    lv_obj_set_height(ui_HighVoltageTxt, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_HighVoltageTxt, 1);
    lv_obj_set_y(ui_HighVoltageTxt, 0);
    lv_obj_set_align(ui_HighVoltageTxt, LV_ALIGN_RIGHT_MID);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_HighVoltageTxt, NULL);
    else lv_textarea_set_accepted_chars(ui_HighVoltageTxt, "1234567890.");
    lv_textarea_set_max_length(ui_HighVoltageTxt, 6);
    lv_textarea_set_text(ui_HighVoltageTxt, "13.35");
    lv_textarea_set_placeholder_text(ui_HighVoltageTxt, "3333");
    lv_textarea_set_one_line(ui_HighVoltageTxt, true);
    lv_obj_set_style_bg_color(ui_HighVoltageTxt, lv_color_hex(0xE6DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HighVoltageTxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HighVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HighVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HighVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HighVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel4 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x381616), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel4);
    lv_obj_set_height(ui_Label4, 30);
    lv_obj_set_width(ui_Label4, lv_pct(70));
    lv_obj_set_align(ui_Label4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label4, "Low   Voltage(V)");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowVoltageTxt = lv_textarea_create(ui_Panel4);
    lv_obj_set_width(ui_LowVoltageTxt, lv_pct(30));
    lv_obj_set_height(ui_LowVoltageTxt, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_LowVoltageTxt, 2);
    lv_obj_set_y(ui_LowVoltageTxt, 0);
    lv_obj_set_align(ui_LowVoltageTxt, LV_ALIGN_RIGHT_MID);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_LowVoltageTxt, NULL);
    else lv_textarea_set_accepted_chars(ui_LowVoltageTxt, "1234567890.");
    lv_textarea_set_max_length(ui_LowVoltageTxt, 6);
    lv_textarea_set_text(ui_LowVoltageTxt, "10.8");
    lv_textarea_set_placeholder_text(ui_LowVoltageTxt, "3333");
    lv_textarea_set_one_line(ui_LowVoltageTxt, true);
    lv_obj_set_style_bg_color(ui_LowVoltageTxt, lv_color_hex(0xE6DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowVoltageTxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LowVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LowVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LowVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LowVoltageTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel5 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel5, 50);
    lv_obj_set_width(ui_Panel5, lv_pct(100));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x381616), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel5);
    lv_obj_set_height(ui_Label5, 30);
    lv_obj_set_width(ui_Label5, lv_pct(70));
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "HIGH  Temp( ºC )");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighTempTxt = lv_textarea_create(ui_Panel5);
    lv_obj_set_width(ui_HighTempTxt, lv_pct(30));
    lv_obj_set_height(ui_HighTempTxt, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_HighTempTxt, 1);
    lv_obj_set_y(ui_HighTempTxt, 0);
    lv_obj_set_align(ui_HighTempTxt, LV_ALIGN_RIGHT_MID);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_HighTempTxt, NULL);
    else lv_textarea_set_accepted_chars(ui_HighTempTxt, "1234567890.");
    lv_textarea_set_max_length(ui_HighTempTxt, 6);
    lv_textarea_set_text(ui_HighTempTxt, "55");
    lv_textarea_set_placeholder_text(ui_HighTempTxt, "3333");
    lv_textarea_set_one_line(ui_HighTempTxt, true);
    lv_obj_set_style_bg_color(ui_HighTempTxt, lv_color_hex(0xE6DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HighTempTxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HighTempTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HighTempTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HighTempTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HighTempTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel6 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel6, 50);
    lv_obj_set_width(ui_Panel6, lv_pct(100));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x381616), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel6);
    lv_obj_set_height(ui_Label6, 30);
    lv_obj_set_width(ui_Label6, lv_pct(70));
    lv_obj_set_align(ui_Label6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label6, "Max Imp(mΩ)");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighImpTxt = lv_textarea_create(ui_Panel6);
    lv_obj_set_width(ui_HighImpTxt, lv_pct(30));
    lv_obj_set_height(ui_HighImpTxt, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_HighImpTxt, 1);
    lv_obj_set_y(ui_HighImpTxt, 0);
    lv_obj_set_align(ui_HighImpTxt, LV_ALIGN_RIGHT_MID);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_HighImpTxt, NULL);
    else lv_textarea_set_accepted_chars(ui_HighImpTxt, "1234567890.");
    lv_textarea_set_max_length(ui_HighImpTxt, 6);
    lv_textarea_set_text(ui_HighImpTxt, "55");
    lv_textarea_set_placeholder_text(ui_HighImpTxt, "3333");
    lv_textarea_set_one_line(ui_HighImpTxt, true);
    lv_obj_set_style_bg_color(ui_HighImpTxt, lv_color_hex(0xE6DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HighImpTxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HighImpTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HighImpTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HighImpTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HighImpTxt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel7 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel7, 50);
    lv_obj_set_width(ui_Panel7, lv_pct(100));
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x381616), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel7);
    lv_obj_set_height(ui_Label7, 30);
    lv_obj_set_width(ui_Label7, lv_pct(70));
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "ALARM");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmSetStatus = lv_switch_create(ui_Panel7);
    lv_obj_set_width(ui_alarmSetStatus, 72);
    lv_obj_set_height(ui_alarmSetStatus, 25);
    lv_obj_set_align(ui_alarmSetStatus, LV_ALIGN_CENTER);


    ui_Panel2 = lv_obj_create(ui_SetRightPannel);
    lv_obj_set_height(ui_Panel2, lv_pct(100));
    lv_obj_set_flex_grow(ui_Panel2, 1);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetBottomPannel = lv_obj_create(ui_SettingScreen);
    lv_obj_set_width(ui_SetBottomPannel, lv_pct(100));
    lv_obj_set_height(ui_SetBottomPannel, lv_pct(10));
    lv_obj_set_align(ui_SetBottomPannel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_SetBottomPannel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SetBottomPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SetBottomPannel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetBottomPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetBottomPannel, lv_color_hex(0x2F2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetBottomPannel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetBottomPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompanyLabel2 = lv_label_create(ui_SetBottomPannel);
    lv_obj_set_width(ui_CompanyLabel2, 120);
    lv_obj_set_height(ui_CompanyLabel2, 15);
    lv_obj_set_align(ui_CompanyLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CompanyLabel2, "IFTECH Co.,LTD");
    lv_obj_set_style_text_color(ui_CompanyLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompanyLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CompanyLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompanyLabel3 = lv_label_create(ui_SetBottomPannel);
    lv_obj_set_width(ui_CompanyLabel3, lv_pct(70));
    lv_obj_set_height(ui_CompanyLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CompanyLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompanyLabel3, "STATUS : NORMAL");
    lv_obj_set_style_text_color(ui_CompanyLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompanyLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CompanyLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionLabel1 = lv_label_create(ui_SetBottomPannel);
    lv_obj_set_width(ui_VersionLabel1, lv_pct(15));
    lv_obj_set_height(ui_VersionLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VersionLabel1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_VersionLabel1, "V1.0.1");
    lv_obj_set_style_text_color(ui_VersionLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VersionLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VersionLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_SettingScreen);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 274);
    lv_obj_set_x(ui_Keyboard1, 236);
    lv_obj_set_y(ui_Keyboard1, -34);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveSettingButton, ui_event_SaveSettingButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HighVoltageTxt, ui_event_HighVoltageTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LowVoltageTxt, ui_event_LowVoltageTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HighTempTxt, ui_event_HighTempTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HighImpTxt, ui_event_HighImpTxt, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_HighVoltageTxt);

}
